"Variants rework" documentation
fluttertools/mix pull request #71
Opened 2022-03-22 22:00 UTC by bdlukaa

Documentation for #70

2022-03-24 00:47 UTC, leoafarias requested changes
I think we should hold a bit on the headless as it's getting it's way into the core of mix.

Let's have a conversation on how to separate that

2022-03-24 00:47 UTC, leoafarias commented on lib/src/attributes/variants/variants.utils.dart
> +  static Variant<T> paragraph<T extends Attribute>() {
Don't think these variants should be  here. Maybe they should get defined within the headless component.

2022-03-24 00:47 UTC, leoafarias commented on lib/src/attributes/variants/variants.utils.dart
> +  static Variant<T> title<T extends Attribute>() {
Same for this variant. I believe any variant for business logic implementation that is not generic for use in the primitives should not be here

2022-03-24 00:47 UTC, leoafarias commented on lib/src/attributes/variants/variants_short.utils.dart
> +final active = VariantUtils.active();
What is an active variant also. Primitives don't have the concept of active, maybe this is part of the headless conversation

2022-04-18 16:59 UTC, bdlukaa commented
@leoafarias do you think #70 should be reverted, then?

2022-04-18 21:50 UTC, leoafarias commented
@bdlukaa will review later and maybe just separate.. give me a couple of days

2022-04-27 20:42 UTC, leoafarias commented
@bdlukaa can we revert #70, and keep all the headless specific things separate?

2022-05-05 13:20 UTC, closed without merging